import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
import Navbar from '@/components/Navbarlatest'
//import Landing from '@/components/Landing1latest'
import Landing from '@/components/Landinglatest'
import Services from '@/components/Serviceslatest'
import Feature from '@/components/Featurelatest'
import List from '@/components/Listlatest'
// import AboutUs from '@/components/AboutUslatest'
import Footer from '@/components/Footerlatest'
 import Contact from '@/components/Contactlatest'
import Home1 from '@/components/Homelatest'
import { Work } from '@/components/Worklatest'
import According from '@/components/Accordinglatest'
import {signIn, useSession} from "next-auth/react"
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet"></link>
        <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="google-site-verification" content="83LjU3ij1FIvWD7zMwXOt7CHlmUN-6cJuoHgcO0wGV8" />
        
      </Head>
      <Navbar/>
      <Landing/>
      <Feature/>
      <List/>
      {/* <Contact/> */}
      <According/>
      {/* <Home1/>
      
      
       */}
      {/* <Work/> */}
      
      
      {/*  */}
      {/* <AboutUs/> */}
       <Footer/> 
    </>
  )
}
